### ISSUE TITLE
Cmake General

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU2_dev#100]
Addressed in Pull Request: #93 

New/Current Cmake rules set up filters for Visual studio projects in the examples folder.
Examples split into header or source, depending on file type. This might want modifying so that include (i.e. public library headers) go somewhere else. 

For the library, filters just mirror disk. 

This may need further adjustment when the library headers are split into public / private headers (by moving private headers to the `src` directory. 

------------------
This issue replaces #91, as a general CMake thing
Work can be found in #93 pull request.

Ideally want all of this solved before Monday 4th Nov
TODO:
+ [x] ~Adjust CMake to auto detect files in given directories~
+ [x] Ensure filtering is as intended e.g. `include` vs `header`
+ [x] Delete all `.vcxproj`/`.sln` (#103)
+ [x] Relocate `.lib` build path
+ [x] Update AppVeyor to use CMake (#103)
+ [x] Does Paul want example binaries to build to same dir? ("just need to add `../../` to line `20` in each example/test `CMakeLists.txt`)
+ [x] Update readme to only talk about cmake

**Comment by Robadob** [comment]
"We do not recommend using GLOB to collect a list of source files from your source tree. If no CMakeLists.txt file changes when a source is added or removed then the generated build system cannot know when to ask CMake to regenerate."

**Comment by Robadob** [comment]
Unsure if `CMAKE_BUILD_TYPE` is working as intended, it appears as an empty variable in CMAKE-GUI and changing it does not affect what options exist within visual studio.
