### ISSUE TITLE
Testing Framework

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU2_dev#102]
@mondus  suggested potentially switching away from boosttest for unit tests. 

`ctest`, `boosttest`, and `googletest` seem to be the popular 3. 

With `cmake` as a dependency `ctest might make the most sense?

**Comment by ptheywood** [comment]
Looks like [Gunrock uses googletest](https://gunrock.github.io/docs/#prerequisites)

**Comment by Robadob** [comment]
Switched to Google test in like November
