### ISSUE TITLE
`notes` directory

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU2_dev#109]
The notes contained within the `notes` directory don't feel like they should be files within the source code, if anything they should be parts of issues, or parts of documentation. 

+ [ ] Duplicate notes content onto issues / documentation (if required)
+ [ ] Remove notes from the repository

**Comment by Robadob** [comment]
* `PaulNotes.txt`: Probably redundant.
* `message-iteration.txt`: this is now redundant.
* `notes.txt`: Most of this is now redundant, largely agrees with what I was saying before I refactored `ModelDescription` hierarchy.

Git claims you're the author, though I'm sceptical so, I vote to delete.

**Comment by ptheywood** [comment]
I'm probably marked as the author from restructuring the repo a while back in the move to cmake. 
I'd agree we can delete this (worst case it exists in history anyway).
