### ISSUE TITLE
Readme needs docs on dependencies

### ISSUE THREAD

**Issue by mondus** [FLAMEGPU/FLAMEGPU2_dev#112]

**Comment by Robadob** [comment]
Boost and doxygen are mentioned under their relevant sections of building the code.
Don't think cpplint is mentioned anywhere.

**Comment by ptheywood** [comment]
Off the top of my head

+ CUDA >= 8 (although we could enforce more-recent CUDA if we wanted)
+ CMake 3.10 or newer (newer is better)
+ Visual studio 2015 or newer (Windows)
+ Appropriate GCC for the CUDA version (linux)
+ Make (linux)
+ *Optional*
    + cpplint for linting (via `pip install --user cpplint`)
    + boost >= 1.54 for testing (although this may not be the best version of boost to use)
    + doxygen (not sure if we have a version dependency
