### ISSUE TITLE
simple_example segfault

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU2_dev#113]
The simple example currently (c9932b6) segfaults under linux:

```
./bin/linux-x64/debug/simple_example 
step: 0
inp msg name: location
Segmentation fault (core dumped)

```

**Comment by Robadob** [comment]
Found the same issue on whatever current master is
![image](https://user-images.githubusercontent.com/742154/68286837-aa835d00-0079-11ea-8a9f-2e6c4a4c1300.png)
Appears `dlist` isn't allocated/initialised, will investigate.
