### ISSUE TITLE
Suppress all warnings from third party code

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU2_dev#133]
Some third party libraries generate warnings with high warning levels (i.e. CUB).

We want to suppress these warnings as they aren't something we will directly fix (although perhaps we should report them). 

This seems to be achievable by either

+ write a header file which includes the offending library with an appropriate `#pragma` beforehand
+ Pass the offending includes to the compiler as system libraries, which for gcc and (recent) msvc will suppress warnings related to files on those paths

https://stackoverflow.com/a/26297816

**Comment by Robadob** [comment]
Testing with this commit
https://github.com/FLAMEGPU/FLAMEGPU2_dev/commit/8f881b0c1beed206af0e82bde643fe66f2ccc8d6

**Comment by Robadob** [comment]
I have a feeling this has been fixed (atleast for visual studio 2019/modern CMake). From memory, the only remaining warning is an obscure NVCC bug where certain includes cause some meaningless template warnings.

**Comment by ptheywood** [comment]
No third party warnings under linux (up to date tools locally + on CI). 

Only warnings that I get at the memont are from swig I believe. 

I'll close this for now as I agree that 3rd party stuff is sorted, but we can always reopen.
