### ISSUE TITLE
CUDAAgentModel Should Notice Dependency Changes.

### ISSUE THREAD

**Issue by Robadob** [FLAMEGPU/FLAMEGPU2_dev#136]
**Issue:**
```c++
    const unsigned int AGENT_COUNT = 5;
    ModelDescription model("model");
    AgentDescription agent("agent");
    AgentPopulation population(agent, AGENT_COUNT);
    Simulation simulation(model);
    SimulationLayer hostfn_layer(simulation, "hostfn_layer");
    CUDAAgentModel cuda_model(ms->model);
    hostfn_layer.addHostFunction(&host_function);
    simulation.addSimulationLayer(hostfn_layer);
    for (unsigned int i = 0; i < AGENT_COUNT; i++) {
        AgentInstance instance = population.getNextInstance();
    }
    model.addAgent(agent);
    cuda_model.setInitialPopulationData(ms->population);
    cuda_model.simulate(ms->simulation); //Exception InvalidCudaAgentMapSize("CUDA agent map size is zero")!
```
If `CUDAAgentModel` is constructed, before all calls to `ModelDescription::addAgent()` have occurred, no agents are allocated within `CUDAAgentModel`, so an exception is thrown when `CUDAAgentModel::simulate()` is called.

**Preferred Behaviour:**
`CUDAAgentModel` notices that it's dependency `ModelDescription` has been changed and automatically reallocates itself/memories.

**Alternate (less desirable) Behaviour:**
* `CUDAAgentModel` performs the allocation the first time `simulate()` is called.
* The exception is changed to stating that `ModelDescription` has changed.

**Fix:**
Description classes have a hash function, or store a timestamp when changed, this can then be tracked by anything dependent on them, to automatically trigger updates.

**Concern:**
If `CUDAAgentModel::setInitialPopulationData()` has already been called, reallocation might necessitate losing this data. How should this be handled?

**Comment by Robadob** [comment]
Same applies to `AgentPopulation` when variables are added to an `Agent` after population has been created.

**Comment by Robadob** [comment]
The description refactor merge has changed behaviour around this, but there is still no explicit blocking.

Creating a `Simulation` now takes a copy of the `ModelData` hierarchy, so the original can still be changed as it is nolonger attached.

Unclear if this needs further work.

**Comment by ptheywood** [comment]
No longer relevant due to copy consruction from refactor?
