### ISSUE TITLE
Replace agent function macros

### ISSUE THREAD

**Issue by Robadob** [FLAMEGPU/FLAMEGPU2_dev#140]
The heavy use of preproccessor macros is ugly and harmful to code parsing.

I have a feeling it might be possible to replace it with templated code on the library side, similar to how thrust and cub require a struct containing `operator()` implementation to be passed to their device reductions.

* User defines a struct with a function of known prototype
* They pass an instance of that struct to the addAgentFunction method, which is templated with a typename for the arg which takes the function name
* The agent function `__global__` kernel wrapper is also templated to take this agent function method
* The pointer to the `__global__` is acquired (which should forcibly instantiate the templated version of it)
* This is then treated much the same onwards, however when launching the device functions you don't have to pass a device function pointer.

-----

Secondary benefit, it removes the calling of a device function via a device pointer. The compiler explicitly cannot optimise across such boundaries, so it might improve performance.

**Comment by Robadob** [comment]
I've produced a mock of how this could work [here](https://gist.github.com/Robadob/3b3a248be18616fd09be24285bb7cf0c) (tested under Visual Studio 2015, CUDA 10.1).

The key difference with how CUB/Thrust handle user provided functions is that ours are a static method, this is because of the difficulty of storing a derived object, and then passing it later on to a `__global__` method, I was unsure how to achieve that (suggestions welcome).

The impact of these differences (with cub/thrust):
* Can't use `operator()`, not allowed for static methods.
* Can't actually suggest they extend a virtual function of a base-class, static methods can't be virtual.
* Templated __global__ doesn't need an instance of the struct containing the function passed to it.

Benefits of this vs current technique:
* We're not passing a device function pointer to the compiler, so it can compile/optimise the whole agent function as a single unit (this seems like the best we can do to reduce the impact of RDC=True).
* Slightly more familiarity to advanced users
* Can still provide macros for less advanced users.

cc @ptheywood @mondus

**Comment by ptheywood** [comment]
Looks like it should be nicer to me, though would probably want tweaking for usability (i.e `#define FLAMEGPU_FUNC static __device__ __forceinline__` or similar.

**Comment by Robadob** [comment]
> Looks like it should be nicer to me, though would probably want tweaking for usability (i.e `#define FLAMEGPU_FUNC static __device__ __forceinline__` or similar.

Yeah that's reasonable,

I've updated the [gist](https://gist.github.com/Robadob/3b3a248be18616fd09be24285bb7cf0c) to include the two macro shortcuts.

Still undecided whether it would be better to keep it closer to cub/thrust (see [1]) in my earlier post, with the presumed negligible cost of doing so. As having the function called `func` isn't very nice.

**Comment by Robadob** [comment]
Interestingly, just noticed `std::binary_function` and `std::unary_function` have been deprecated and C++11 and don't actually define a virtual function, it's simply a guide for correctly implementing the required operators.

http://www.cplusplus.com/reference/functional/binary_function/
