### ISSUE TITLE
Agent Random Total Thread Size Calculation

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU2_dev#141]
When grid size does not match state list size, a device assert can be triggered by accessing randoms due to the TID being greater than the total number of randoms generated

This is semi-hardware dependent - the occupancy calculator needs to suggest more threads than agents (or just suggest a non-multiple of 32 agents should trigger this)

Some possible options to
+ Make sure that idle threads are terminated immediately
+ Run the occupancy calculator for each kernel per layer to calcuated required number of randoms early

A temproary fix is to always add some number of extra randoms (i.e. max block size for the device)

**Comment by Robadob** [comment]
> Make sure that idle threads are terminated immediately

I've applied this change inside `host_functions_2` branch (#138).

The wrapper kernel is terminating threads, it's simply initialising the `FLAMEGPU_API` object first (setting vars, besides the `AgentRandom` object throwing assertions).
