### ISSUE TITLE
Thrust Include Path

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU2_dev#143]
Thrust shipped with CUDA 10.1 generates warnigns with our warning level.

Providing the more recent thrust version resolves this on windows, but with current (at time of writing) Cmake rules the cuda included thrust is used, rather than from the externals dir. 

This *should* be fixable with compiler flags via cmake, but so far no success. 
Instead, simply moving/deleting the cuda 10.1 thrust lets the repo-provided thrust take precedent. 

This is **horrible** and needs fixing propperly at some point (ideally sooner rather than later).

`travis_install.sh` will then need the horrible fix removing.
```
rm -rf /usr/local/cuda-${CUDA_SHORT}/targets/x86_64-linux/include/thrust
```

**Comment by ptheywood** [comment]
running the nvcc command with `-v` for verbose output, the actual command includes ` "-I/usr/local/cuda-10.2/bin/../targets/x86_64-linux/include"`.
I.e. this has precedence over `-isystem "/home/ptheywood/code/flamegpu/flamegpu2_dev/externals"`

**Comment by ptheywood** [comment]
This is now resolved, although from CUDA > 10.2 we **shouldn't** have to ship our own version of thrust.

**Comment by ptheywood** [comment]
Cmake 3.16 appears to reintroduce the warnings for me, using the system thrust in place of the user-specified thrust again. 

Specifically cmake `3.16.3` on ubuntu 18.04, using CUDA 10.2. 

```
[ 61%] Building CUDA object FLAMEGPU2/CMakeFiles/flamegpu2.dir/flamegpu/runtime/flamegpu_host_api.cu.o
/usr/local/cuda-10.2/bin/../targets/x86_64-linux/include/thrust/system/cuda/detail/cub/block/block_exchange.cuh(718): warning: the initialization of member "thrust::cuda_cub::cub::BlockExchange<InputT, BLOCK_DIM_X, ITEMS_PER_THREAD, WARP_TIME_SLICING, BLOCK_DIM_Y, BLOCK_DIM_Z, PTX_ARCH>::lane_id" will be done before that of member "thrust::cuda_cub::cub::BlockExchange<InputT, BLOCK_DIM_X, ITEMS_PER_THREAD, WARP_TIME_SLICING, BLOCK_DIM_Y, BLOCK_DIM_Z, PTX_ARCH>::warp_id"

/usr/local/cuda-10.2/bin/../targets/x86_64-linux/include/thrust/system/cuda/detail/cub/device/dispatch/../../agent/agent_select_if.cuh(250): warning: the initialization of member "thrust::cuda_cub::cub::AgentSelectIf<AgentSelectIfPolicyT, InputIteratorT, FlagsInputIteratorT, SelectedOutputIteratorT, SelectOpT, EqualityOpT, OffsetT, KEEP_REJECTS>::d_selected_out" will be done before that of member "thrust::cuda_cub::cub::AgentSelectIf<AgentSelectIfPolicyT, InputIteratorT, FlagsInputIteratorT, SelectedOutputIteratorT, SelectOpT, EqualityOpT, OffsetT, KEEP_REJECTS>::d_flags_in"

/usr/local/cuda-10.2/bin/../targets/x86_64-linux/include/thrust/system/cuda/detail/cub/device/dispatch/dispatch_radix_sort.cuh(1374): warning: the initialization of member "thrust::cuda_cub::cub::DispatchSegmentedRadixSort<IS_DESCENDING, KeyT, ValueT, OffsetIteratorT, OffsetT>::stream" will be done before that of member "thrust::cuda_cub::cub::DispatchSegmentedRadixSort<IS_DESCENDING, KeyT, ValueT, OffsetIteratorT, OffsetT>::is_overwrite_okay"
```

cmake `3.15.3` on the same machine correctly uses the user-provided thrust rather than cuda-provided thrust

```
[ 61%] Building CUDA object FLAMEGPU2/CMakeFiles/flamegpu2.dir/flamegpu/runtime/flamegpu_host_api.cu.o
[ 64%] Building CUDA object FLAMEGPU2/CMakeFiles/flamegpu2.dir/flamegpu/runtime/messaging/BruteForce.cu.o
```

**Comment by Robadob** [comment]
It will be that new CMake is changing either the order of include, or the include flags for CMake. Remember we packaged newer thrust with fgpu2 to bypass this issue.

**Comment by ptheywood** [comment]
```
3.15
cd /home/ptheywood/code/flamegpu/flamegpu2_dev/build_cmake_15/FLAMEGPU2 && /usr/local/cuda-10.2/bin/nvcc   -I/home/ptheywood/code/flamegpu/flamegpu2_dev/include -I/home/ptheywood/code/flamegpu/flamegpu2_dev/src -isystem=/home/ptheywood/code/flamegpu/flamegpu2_dev/externals -isystem=/usr/local/cuda-10.2/targets/x86_64-linux/include/../include  -DMIN_ARCH=61  -gencode arch=compute_61,code=sm_61 -gencode arch=compute_61,code=compute_61 --expt-relaxed-constexpr --Wreorder -Xcompiler -Wall -O3 -DNDEBUG -lineinfo   -std=c++14 -x cu -dc /home/ptheywood/code/flamegpu/flamegpu2_dev/src/flamegpu/util/compute_capability.cu -o CMakeFiles/flamegpu2.dir/flamegpu/util/compute_capability.cu.o


3.16
cd /home/ptheywood/code/flamegpu/flamegpu2_dev/build/FLAMEGPU2 && /usr/local/cuda-10.2/bin/nvcc   -I/home/ptheywood/code/flamegpu/flamegpu2_dev/include -I/home/ptheywood/code/flamegpu/flamegpu2_dev/src -isystem=/home/ptheywood/code/flamegpu/flamegpu2_dev/externals  -DMIN_ARCH=61  -gencode arch=compute_61,code=sm_61 -gencode arch=compute_61,code=compute_61 --expt-relaxed-constexpr --Wreorder -Xcompiler -Wall -O3 -DNDEBUG -lineinfo   -std=c++14 -x cu -dc /home/ptheywood/code/flamegpu/flamegpu2_dev/src/flamegpu/util/compute_capability.cu -o CMakeFiles/flamegpu2.dir/flamegpu/util/compute_capability.cu.o
```

3.16 is not passing the additional `-isystem=/usr/local/cuda-10.2/targets/x86_64-linux/include/../include` which we have added to mark that directory as a system include for order of precedence, it must be detecting that the evaluated directory is already known by the nvidia compiler so is intentionally not providing it?

**Comment by ptheywood** [comment]
removing `SYSTEM` from the `${FLAMEGPU_ROOT}/externals` include target statements appears to resolve this issue, while not re-introducing it in 3.15. 

as far as I can tell there are currently no visible downsides to this?

**Comment by ptheywood** [comment]
`cmake 3.17.0-rc3` doesn't suffer from this issue, as it also passes `-isystem=/usr/local/cuda-10.2/targets/x86_64-linux/include/../include` as intended, influencing include order. 

infact the `../include` is no longer needed either to ensure that the -isystem setting is included...

**Comment by Robadob** [comment]
Only affects you/travis, so you may aswell fix it however you see fit.
