### ISSUE TITLE
Optional (Brute Force) Messages

### ISSUE THREAD

**Issue by Robadob** [FLAMEGPU/FLAMEGPU2_dev#168]
Currently looking at this. Two points of query/concern.

1.
`d_scan_flag` is used to mark when a message has been written to (and is later exclusive summed, to manage the scatter of all written messages into a contiguous block). 

Should this array exist once globally? Or once per Message type?

Should this array be some global define? Or passed as a variable?

I'm on the side of a single global, similar to how device random is handled.

2.
Sorting/scattering messages requires a movement for each variable. Without a significant rework, this will require launching a kernel per variable. However, I expect this is something we will want to avoid.

**Comment by ptheywood** [comment]
Flame 1 uses a single  kernel launch per agent/message type which moves all variables belonging to that message/agent, which is probably the best compromise. Has scatter in the name I believe.

**Comment by Robadob** [comment]
Yes I realise, however that's not (easily) possible with programmatically
defined messages.

Would need to pass a list of pointers and type sizes to the kernel, as it
can't be hard coded.

I've currently just launched 1 kernel per variable.

**Comment by Robadob** [comment]
This was discussed in an informal meeting.

I think it was agreed that, due to the parity with sorting agents (e.g. on death [#49]), we would make some kind of generic function for passing in an array of structs to perform this multi variable reorder within a single kernel.
