### ISSUE TITLE
Python bindings

### ISSUE THREAD

**Issue by mondus** [FLAMEGPU/FLAMEGPU2_dev#174]
An interesting example

https://groups.google.com/forum/#!topic/thrust-users/GGWw_uHPfGs

**Comment by ptheywood** [comment]
Related to #179 #180

**Comment by Robadob** [comment]
Whilst I'm setting up SWIG to work on Windows, I'll log some notes of what's required.

* Download `swigwin-4.0.1` from here: http://www.swig.org/download.html
* Extract it somewhere.
* In Cmake config, turn on `BUILD_SWIG_PYTHON`
* Set cmake var `SWIG_EXECTUABLE` to extracted path of `swig.exe`, should be in root.

* Set Env vars (e.g.): (This is from the docs, i'm not sure if CMake version actually requires it yet)
    * `PYTHON_INCLUDE: D:\python21\include`
    * `PYTHON_LIB: D:\python21\libs\python21.lib`

-------------
![image](https://user-images.githubusercontent.com/742154/82125925-179e4a80-97a1-11ea-9e3d-4d785d7487da.png)
Had this weird error when i tried to reconfigure with vs2015. Deleted cache and went with 2019 and it went away. Might be reconfigure issue, might be vs2015 issue.

**Comment by Robadob** [comment]
SWIG has been in master for a while (#291) and all new PRs should also have SWIG support, hence closing.
