### ISSUE TITLE
Concurrency within Layers

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU2_dev#189]
With FLAME GPU 2 we should be able to achieve concurrency using streams in various places. 

E.g. concurrent agent functions within layers. 

building a DAG with good dependency analysis rather than explicit layers would allow this to be taken further. 

This will need to account for which agent functions can be executed concurrently. 

I.e. a layer with 2 agent functions, for 1 agent type with a common state as a common input/output. This should not be executed concurrently / be allowed within a single layer.

CuRVE will need adjusting to make it non-blocking, streams will be needed everywhere appropriate, and maybe events. Care will need to be taken with `__constant__` cache. 

### Rough plan:

+ Restructure `CUDAAgentModel::step()` into smaller parts
    + See below for possible outline 
+ Construct streams upfront, based on maximum required in any given layer.
+ Ensure all operations within a layer are async with streams.
+ Make as  much async as possible with streams for pre/post-layer data management?
+ ...

### `step` refactor outline
Details the current logical structure, how a serial refactor could look and how a parallel refactor could look

#### Current step function 
effectively, some difference between logic + impl

```cuda
current_step_effective(){

    // init singletons

    // step value resetting (message lists etc.)

    // Iterate layers
    for(auto & layer: layers){

        // reset flags/counters/singletons

        // Iterate functions
        for(auto & func: layer->functions){

            if(condition){
                // register variables for condition

                // do condition (sync), map of functions that need executing

                // unmap condition variables
            }

            if(!condition or condition_passed){
                // map agent

                if(in_message){
                    // map in_message
                }
                if(out_mesasge){
                    // map out_message
                }

                // exec agent function

                // post-message stuff
                if(in_message){
                    // un map in_message + post process
                }

                if(out_mesasge){
                    // un map out_message + post process
                }

                // death

                // agent state transitions

                // birth

                // unmap
            }
        }

        // host layer functions

        // process host agent birth

    }

    // step functions

    // process host agent birth

    // exit conditions

    // step_counter++

    // tidy up

    // return success of exit conditions

}
```

#### Sequential refactored version strucutre

Aproximate. Synchronous ops (memcpy) will block parallelism even if streams used correctly.

```cuda
step_restructure_sync(){

    step_initialisation() // init singletons + reset any values 

    // Iterate layers
    for(auto & layer: layers){

        layer_pre(layer) // reset any flags our counters on a per layer basis

        // Iterate functions
        for(auto & func: layer->functions){


            do_function_condition(func) // register, do, unregister. Store /return success

            if(run_function){
                do_function(func); // map agent/messages, exec, unmap/postprocess/death/birth 
            }
        }

        do_host_functions(layer);// host functions
        processHostAgentCreation(); // Process host agent birth from layer

    }


    do_step_functions() // step functions
    processHostAgentCreation(); // Process host agent birth from step

    exit_required = do_exit_conditions() // exit conditions

    post_step() // tidy up, step_counter++

    return !exit_required;

}
```

#### Parallel refactored which might enable concurrency

To get concurrency on windows need to issue async commands wide rather than tall. 

Note that async memcpy will require mallocManaged(pinned=true) host memory for data being copied (to avoid paging). This might have to be a secondary step to kernel concurrency.
Might be better to use events in the default stream for sync than device - in case any longer running async ops? (long term opt.)

```cuda
step_restructure_async(){

    step_initialisation() // init singletons + reset any values 

    // Iterate layers
    for(auto & layer: layers){

        layer_pre(layer) // reset any flags our counters on a per layer basis

        // do_function_condition_conc
        {
            map_conditions_sync(layer->functions) // s
            function_conditions_async(layer->functions, streams)
            conditon_results_async(layer->functions, streams) // issue async memcpies in each stream together for wddm concurrency. Async might not help with 4B copies, as latency costs more than data transfer. probably better to just do a 4b*function copy.
            unmap_conditions_sync() // This has to be synchrnonous currently
        }

        // container of functions to exec / store internally 
        funcs_to_exec = layer->functions if not function_condtion_fail
        // do_agent_functions_conc
        {
            map_agent_functions_sync(funcs_to_exec)
            message_prep_sync(funcs_to_exec) // This might be able to be async, need to look at mesage impl.
            agent_func_async(funcs_to_exec, streams)
            message_post_sync(funcs_to_exec); // probably includes memcpy, do them together after kernels have been launched.
            unmap_agent_functions_sync(funcs_to_exec)
            death_sync(funcs_to_exec) // Might get some concurrency in here, but the func needs to sync. wrt streams involved /
            agent_state_transition_sync(funcs_to_exec) // Might get some concurrency in here, but the func needs to sync. wrt streams involved /
            agent_state_transition_sync(funcs_to_exec) // Might get some concurrency in here, but the func needs to sync. wrt streams involved /
            birth_sync(funcs_to_exec) // Might get some concurrency in here, but the func needs to sync. wrt streams involved /
        }

        do_host_functions(layer);// host layer functions

        processHostAgentCreation(); // Handle any agent output from host layer functions, could run in parallel no guarantee  user isn't creating race conditions.

    }


    do_step_functions() // step functions
    processHostAgentCreation(); // Handle any agent output from step functions


    exit_required = do_exit_conditions()

    post_step() // tidy up, step_counter++

    return !exit_required;

} 
```

## Testing Concurrency
Currently unsure how we could test concurrency programatically. 

1.Define a test model with multiple agent types / multiple states (all cases which should have concurrency
2. Need to add cuda events before and after the agent func in appropriate streams
3. Afterwarrds, using the start and end times of the kernels, there *should* be some overlap in the windows. 
4. Alt add a way of running without concurrency (might be useful for debugging anyway?)

## RTC vs cuda runtime api.
There is likely to be a decent bit of duplication in here for rtc support. It might be better to abstract this logic out into a separate class. 

I.e. have a `CUDAAgentFunction` class which takes a `functionDesctiption`, instanciated on creation of the `CUDAAgentModel`? This would do the if normal else rtc kidn of logic and jsut present methods to `map()`, `pre()`, `run(stream)`, `unmap()`, `post()`, etc?

Or maybe make `CUDAAgentFunction` abstract, with concrete specialisations for normal and rtc versions - this would possibly be a way of preventing RTC from being left behind - new features must go into the base class, leading to RTC not being usable until all features implemented.

**Comment by Robadob** [comment]
> Ensure all operations within a layer are async with streams.

I started thinking about, Async host code. As widely as possible we should make use of [`shared_timed_mutex`](shared_timed_mutex) (we don't actually need to make use of timed functionality, but the reduced interface version is c++17).

All C++ collections, are multiple read, unique write. So with `shared_mutex`, get `shared_lock` if reading, get `unique_lock`. There are 3 cases where I think this may be necessary.

* `EnvironmentManager`: Heavily uses C++ maps, `unique_lock` probably only required for `init()`, `add()` and `remove()`. `set()` isn't updating the map, just a value within the map. That's technically unsafe (race condition), but even if we did protect from race condition, if a user is doing multiple sets/reads from different host functions in the same layer thats on them (we could probably make some expensive debug check if really necessary).
* `Curve`: This has a custom map implementation, so similar rules to above are likely to apply. Regsitering/unregistering vars will require `unique lock`, reading curve (aka when we commit it to device) can used `shared_lock`.
* `CUDAAgent`: The `CUDAAgent` refactor with submodels makes agent-states/sub-agents share buffers used for agent output. This is currently implemented with regular mutex (I wasn't aware of shared). This implementation should be reviewed, although I'm not 100% sure there's a case for using shared mutex. (If my proposal from #228 is implemented, that would take the place of `CUDAAgent`.
* `HostAPI`: Would need to consider if this has any non-threadsafe operations (e.g. rng), which need addressing. Off the top of my head, the main concern would be host agent output, as that stores agents to a structure within `HostAPI` instance (or it might be `CUDAAgentModel`). These would require a `unique_lock` to perform the output. The output is actually processed after the layer though, so the method which handles that `CUDAAgentModel::processHostAgentCreation()` would handle the reads and may need handling if we want to make it parallel

**Comment by ptheywood** [comment]
by async I was generally only considering single host thread and using the async version of cudaMemcpy etc, rather than concurrent host threads (too much of flamegpu isnt' thread safe as you've highlighted). 

I'm sure there is merit to supporting concurrency on the host, but it may be worth making it a longer term issue so it doesn't get lost when on-device concurrency is implemented.

**Comment by Robadob** [comment]
As a minimum, supporting async curve/environment will be required in case a user wants to run two instances of `CUDAAgentModel` (although in this respect, they will also need to account for device index too presumably).

Regardless, these asyncs should be fairly straight forwards to implement in most cases. Just a case of throwing locks inside a bunch of methods.

**Comment by ptheywood** [comment]
Having experimented some more with a test repo [ptheywood/cuda-concurrency-detection](https://github.com/ptheywood/cuda-concurrency-detection) I'm confident that we can write a (carefully construted) test which will allow us to detect concurrency within a layer. 

+ [ ] Add cuda event timers in the default stream within the layer, to time how long the batch of work took
    + This will have to be for the agent functions within the layer only, i.e. not include memcpy or function conditions etc.
+ [ ] Add a way to access this timing info progrmatically (only needed for the test suite).
+ [ ] Add an argument/method to restrict the use of streams within a layer.
    + default to allow streams and use as many as possible, but allow it to be disabled.
+ [ ] Carefully construct a test case with knowledge of the device being tested on.
    + [ ] Multiple agent functions, each doing pointless work that takes ~ 100ms+
    + [ ] Total number of blocks launched across all of the agent functions needs to be less than the total to achieve full occupancy of the device to ensure concurrency is possible. I.e. small populations.
    + [ ] Get an average runtime of the layer when using 1 stream
    + [ ] Get an average runtime of the layer when using N streams.
    + [ ] Compare average runtimes, and ensure it's sufficenrtly faster (sufficient depends on the exact test composition, but should be trivial to construct a case with 2x+ speedup.
