### ISSUE TITLE
How many agents aprox. FLAMEGPU2 will support?

### ISSUE THREAD

**Issue by eze1981** [FLAMEGPU/FLAMEGPU2_dev#20]
Hi,

How many agents are you expecting to be able to run on the same simulation? In 2010 FLAME was designed for 10^6 agents ([http://www.ifaamas.org/Proceedings/aamas2010/pdf/04%20Demos/D-10.pdf]). Are you expecting to run more?

Regards,
Ezequiel

**Comment by mondus** [comment]
Hi @eze1981. Current FLAME GPU is limited to only a single device. The number of agents which can be simulated has grown as GPU device memory has increased. The number supported obviously also depends on the amount of agent memory used. FLAME GPU 2 will support models which are spanned over multiple devices (i.e. massive models). This will allow up to 8x larger agent populations (on say a DGX-1 GPU system). The real benefit from larger population sizes will come from being able to run multiple simulations at once. Thanks for your interest in FLAME GPU 2. We still have lots to do before we get to any form of release however!

**Comment by eze1981** [comment]
Thank you @mondus  for your response.
