### ISSUE TITLE
Reserved variable names

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU2_dev#206]
To prevent users from specifying variable names which would result in curve conflicts for flamegpu compulsory features, it might be best to prevent variables being declared with certain names, or names which follow a pattern.

~E.g. following unix file name conventions, if the variable string name begins with `.` it could be reserved. This would then only require that at variable definition time the string is checked to not begin with `.`.~

Variables that begin with `_` shall be reserved. A single character check should be cheap and work for variable names of any length.

However, setting the variable may still be achievable if it exists by default without adding (potentially) expensive additional runtime checks on the host and the device to prevent users from setting these values (while allowing internal properties to set them?) 

-----------

~~**As of #218 it has also become necessary to prevent users creating agent's with variables `name` and `state` (due to the xml output format).**~~ *(This was completed within the PR)*

**Comment by Robadob** [comment]
spatial messaging already prevent redeclaration of x, y, z var (by
declaring it in constructor).

Array messaging plans to use internal `___INDEX`, again this will be
blocked, but it's possible a user could override the value with CURVE in
their agent function, I haven't considered a good way of avoiding that
thusfar.

**Comment by Robadob** [comment]
As discussed in meeting, var names must be atleast len 1, so applying this is easy (just device side get/set methods, and agent instance get/set methods check first char). Question is whether we want it debug only.

Similarly, array msg internal will need updating to fit the pattern.

**Comment by ptheywood** [comment]
I'd expect people to use release by default to be honest (why bother with GPUs if you're going to be running >10x slower?).

For now I'd just do it everywhere, or prep a `#define` to opt out, but leave it on by default. It falls back again to do we want an extra target for release without checks which might be a little bit quicker?

**Comment by Robadob** [comment]
Assigned it parity, given array messages already use a 'reserved' var.
