### ISSUE TITLE
Documenting Travis CI 

### ISSUE THREAD

**Issue by mozhgan-kch** [FLAMEGPU/FLAMEGPU2_dev#21]

**Comment by mondus** [comment]
Travis CI build seem to be failing for  dev/1-4 but passing in appveyor CI. The error relates to missing `cuda_runtime.h` however the logs suggest that CUDA is installing correctly. Needs investigating.

**Comment by mondus** [comment]
This is now fixed by @mozhgan-kch following an update to the make file.
