### ISSUE TITLE
FLAME GPU 1 Standard output

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU2_dev#210]
FLAME GPU 1 prints various things to stdout, e.g.

```
Processing Simulation Step 1
Processing Simulation Step 2
Total Processing time: 2.320352 (ms)
```

Do we want to do this? It might be useful for progress checking. 

It might be better to hide (some of) this output behind a default flag, such as `-v/--verbose` for the `Processing Simulation Step N` messages, and `-t/--timing` for the timing information?

This may become more complex with submodels.

**Comment by Robadob** [comment]
Make it a simulation config option which is on by default.

**Comment by Robadob** [comment]
And make it print step count on the same damn line, no one wants to flood console with a counter.

**Comment by ptheywood** [comment]
> And make it print step count on the same damn line, no one wants to flood console with a counter.

This only works if nothing else is output to stdout (i.e. stuff from a step function).

It can also be useful for post-processing of log files, though it would be better to just write a step func to do the processing instead / let people write their own CSV files etc.

**Comment by Robadob** [comment]
> This only works if nothing else is output to stdout (i.e. stuff from a step function).

Add host function print method so you can detect that and undef `printf` etc :s
