### ISSUE TITLE
Automatically Initializing Agents

### ISSUE THREAD

**Issue by chathika** [FLAMEGPU/FLAMEGPU2_dev#22]
Hi,

According to my understanding the agents of a simulation run must be specified individually in the XML file under the "iterations" directory. Is there a way to automatically generate agents within the code itself instead of manually specifying the agents, individually?

Thank you!
Chathika

**Comment by mondus** [comment]
Hi @chathika FLAME GPU 2 will have a full run-time API which will allow the specification of agent using procedural code. i.e. You will be able to create agents dynamically before model execution. Something a bit like the below from one of our current tests.

```
    AgentPopulation population(circle_agent, 100);
    //add 100 instances (no problem)
    for (int i = 0; i< 100; i++)
    {
        AgentInstance instance = population.getNextInstance("default");
        instance.setVariable<float>("x", i*0.1f);
    }
```

XML defined models and initial states will still be supported but will have a 1-to-1 mapping with the FLAME GPU API calls which will simplify the current templates.

With respect to generating agents during the execution of the model. This is already supported by FLAME GPU. The pedestrian examples show how agent outputs can be used to generate new agents as part of the model execution.
