### ISSUE TITLE
Visualisation target in visual studio

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU2_dev#231]
In visual studio (and maybe makefiles), add a custom target for visualisation_release, visualisation_debug builds, if cmake was configured with VISUALISATION=ON (for dependencies).

This would need setting in a similar vein to the profile generator target.

Whether or not we want this on linux is questionable, having sepearate cmake build directories is trivial, although the main library is built multiple times in this case.

**Comment by mondus** [comment]
To be one with a global CMAKE flag. Can we disable visualisation via model arg for things built with vis?
