### ISSUE TITLE
RTC does not discriminate between scalar and array variables

### ISSUE THREAD

**Issue by mondus** [FLAMEGPU/FLAMEGPU2_dev#234]
E.g. If a scalar variable is to be accessed in an agent function nothing stops a call to `getArrayVariable()`. This would require `typeid `on the device or an additional variable to store the size.

**Comment by Robadob** [comment]
Even if you had `typeid` on device, you would need to store the type in an additional variable.

The option for explicit type checking of expected/known types, without access to `typeid` by using explicit template specialisation.

```
enum ManualTypes { Unknown = 0, Float = 1,};
template<typename T>
int myType() {
    // default type (for unknowns)
    return ManualTypes.Unknown;
}
template<>
int myType<float>() {
    return ManualTypes.Float;
};

```

This should be device capable.

**Comment by mondus** [comment]
Thinking about this overnight I don;t think I need any type id stuff as I can just log the array size in curve_rtc and put an explicit check in the dynamically generated code. There is no way to check the type size of the actual variable though without doing what you suggest above. I would say that this is more of a low priority feature.
