### ISSUE TITLE
HostEnvironment::add should be removed

### ISSUE THREAD

**Issue by mondus** [FLAMEGPU/FLAMEGPU2_dev#244]
This should be removed. It should not be possible to create new environment variables in step functions as this is impossible to map to RTC which requires a fixed set of variables in the model description at compile time (e.g. first call to step).

There are also no modelling use cases for this outside of the text_host_environment.cu tests.

**Comment by mondus** [comment]
Should also then remove EnvironmentManager::defragement() e..g. no arguments version called only by add()

**Comment by mondus** [comment]
Also get rid of EnvironmentManager::remove()

**Comment by Robadob** [comment]
> Also get rid of EnvironmentManager::remove()

Have removed `HostEnvironment::remove()`, `EnvironmentManager` version will remain, even if it's only as a demonstration to better aid in understanding the internal workings of `EnvironmentManager`.
