### ISSUE TITLE
Handling multiple functions added to the same simulation layer

### ISSUE THREAD

**Issue by mozhgan-kch** [FLAMEGPU/FLAMEGPU2_dev#25]
In FLAMEGPU2 we are allowed to add multiple functions to the same simulation layer. We need to check if these functions belong to the same agent or not. Are these functions independent of each other?

```
    SimulationLayer moveStay_layer(simulation, "move_layer");
    moveStay_layer.addAgentFunction("move");
    moveStay_layer.addAgentFunction("stay");
    simulation.addSimulationLayer(moveStay_layer);
```

**Comment by mondus** [comment]
This is required. The check should test to make sure that when a function is added there is no other function in the layer which operates on agents within the same statelist.

**Comment by ptheywood** [comment]
This is working now.
