### ISSUE TITLE
DerivedException Wformat-security warning for gcc debug builds

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU2_dev#254]
Debug build under linux generates many `Wformat-security` warnings

i.e.
```
/home/ptheywood/code/flamegpu/flamegpu2_dev/include/flamegpu/exception/FGPUException.h: In constructor ‘VisualisationException::VisualisationException(const char*, ...)’:
/home/ptheywood/code/flamegpu/flamegpu2_dev/include/flamegpu/exception/FGPUException.h:366:38: warning: format not a string literal and no format arguments [-Wformat-security]
 DERIVED_FGPUException(VisualisationException, "An exception prevented the visualisation from working.");
```

This should be resolved.

**Comment by Robadob** [comment]
Ah, I think this is added by the new code Paul added to exceptions.

Line 63: `        fprintf(stderr, err_message.c_str()); \`

Changing it to: `        fputs(err_message.c_str(), stderr); \` or `        fprintf(stderr, "%s", err_message.c_str()); \` should work
