### ISSUE TITLE
runtime mapping of variables

### ISSUE THREAD

**Issue by mozhgan-kch** [FLAMEGPU/FLAMEGPU2_dev#26]
Currently, the `mapRuntimeVariables` function, does the mapping for all the variables. It's been agreed to modify this later, so we only map the variables that are used within a function during the simulation.

**Comment by mondus** [comment]
This is much later. Perhaps for milestone 2 after first alpha release.

**Comment by Robadob** [comment]
Closing, not convinced this is still on the roadmap.
