### ISSUE TITLE
Standalone Models

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU2_dev#261]
Users should not be expected to have thier examples in the examples directory (although this should still be an option for anyone wishing to contribute a new example).

Instead, users code should be able to be tracked in it's own repository, with a simple method of defining their example (CmakeLists.txt) with the main flamegpu2 library either:

+ installed on the system globally (/per user)
+ built from a local directory
    + via submodule?
    + via cmake download

This will probably need to take the form of a new repository as a bare-bones example which users can copy as a starting point.

i.e. the following files should be sufficient - essentiallly and example.

+ `LICENCE`
+ `Readme.md`
+ `CMakeLists.txt`
+ `src/`
    + `main.cu`
+ `tests/`
    + `...`

The contents of `CMakeLists.txt` will be the difficult bit / main difference between this and examples in the main repository - as flamegpu2 will need to be found for `common.cmake` to be included and usable.

We will likely want several versions of this for the different ways to work with flamegpu2, although ideally with minimal differences.

+ C++ 
+ Python
+ **Maybe**  C++ RTC, but probably not (no one should use this tbh)

**Comment by ptheywood** [comment]
Just discovered [github template repositories](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-template-repository)

**Comment by Robadob** [comment]
> Just discovered [github template repositories](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-template-repository).
> 
> [Usage](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-from-a-template)

Just looks like forking without keeping the historic commits. Nothing against it though.

**Comment by ptheywood** [comment]
Exaclty, which is a good thing (for individual projects in their own repositories which just include the main library via cmake or a submodule etc). 

No need for every flamegpu model in the world to be a fork of `flamegpu/flamegpu2_empty_example` or whatever it would be called.

**Comment by Robadob** [comment]
There would be no harm in a directory of projects using it as a template though (aka forks).

**Comment by Robadob** [comment]
https://github.com/FLAMEGPU/flamegpu2_example_template

I've setup a template example repo that works.
Remaining todo:
* Tweak the model so it's not just a copy of circles
* Mention it in the main flamegpu2 readme

**Comment by ptheywood** [comment]
Should we reopen this but with checkboxes for c++ and python ones? (so we don't forget to do this for python?)

**Comment by Robadob** [comment]
I don't personally consider python an issue until python is ready. I'd rather it be added to the OP of swig issue/PR.
