### ISSUE TITLE
Feature: Agent Array Variables

### ISSUE THREAD

**Issue by mozhgan-kch** [FLAMEGPU/FLAMEGPU2_dev#27]
Perhaps for milestone 2 after first alpha release.

**Comment by Robadob** [comment]
I think this is my next task to work on, long list of things to check off (will move list to PR once I break ground):

- [x] Agent variable definition
* Default's work via:
    - [ ] `AgentPopulation`
    - [ ] Host Agent Birth
    - [ ] Device Agent Birth
* `FLAMEGPU_DEVICE_API`:
    - [ ] `getVariable()` works
    - [ ] `setVariable()` works
* `FLAMEGPU_HOST_API`:
   - [ ] Exception thrown if trying to reduce array variables (can't support these, as i don't think CUB supports strided accesses)
* Miscellaneous tests; Do array values persist through:
   - [ ] host agent birth scatter
   - [ ] device agent birth scatter
   - [ ] agent death scatter (for the living agents)
   - [ ] agent state transition scatter
   - [ ] agent function condition scatter (agents are sorted so disabled agents goto front of array)

Possibly other items to add to the above list, which I've missed off the top of my head.

From discussing this with @ptheywood, it was unclear whether we wanted to allow users to set/get the full array (as a `std::array<T, N>`) on the device, or limit them to individual variable accesses. The prior may have performance implications for large arrays. I don't see any harm in providing both and assuming users will use them carefully (perhaps with some documentation to hint). Haven't actually tested that `std::array` works on device, so this might all be moot.
