### ISSUE TITLE
Compute Capability Validation

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU2_dev#278]
Using Cmake it's possible to find which compute capabilities are valid for the current compiler (through string manipulation of `nvcc --help`). 

This will better allow us to validate the `-DSMS` argument at configure time, instead of waiting till the first CUDA file is compiled (and simplify setting default CCs we compile for).

This is currently in a separate repo, tested under linux but awa

I'm also tempted to change the name of the cmake option from `SMS`, although convenient it's a little ambiguous, as they are SM architectures rather than SM counts or similar. `CC` however is a bad option, as it typically refers to the `C` compiler, and `arch` is a bad option, as it often refers to the host architecture for optimisation (x64, etc).

+ [x] Dynamic compute capability validation / Simple to change defaults.
+ [x] **Maybe** Rename the -DSMS option?
    + `-DCUDA_ARCH`
    + Thoughts @Robadob @mondus @mileach

**Comment by Robadob** [comment]
Just call it `cuda_arch` or more explicit `cuda_code_generation`, given the vs option is `code_generation`.

**Comment by ptheywood** [comment]
`CUDA_ARCH` makes sense / isn't too long. 

Could add `-DSMS` as a deprecated option for backcompat with FLAME GPU 1, but given we're switching to cmake the build process has changed anyway so I don't think it's neccesary.
