### ISSUE TITLE
Type check for setVariable and getVariable funcs

### ISSUE THREAD

**Issue by mozhgan-kch** [FLAMEGPU/FLAMEGPU2_dev#28]
Type check is required for below functions :
`template<typename T, unsigned int N>
__device__ T FLAMEGPU_API::getVariable(const char(&variable_name)[N]);`
and 
`template<typename T, unsigned int N>
__device__ void FLAMEGPU_API::setVariable(const char(&variable_name)[N], T value)`

**Comment by ptheywood** [comment]
RTTI functions are not supported in device code (https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#rtti)

We probably can't do this.
