### ISSUE TITLE
Switch to Github Actions for CI

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU2_dev#290]
> tldr; I've figured out cuda on windows/linux github actions so we can ditch appveyor and have faster (more concurrent) CI builds

Github actions as CI has a few advantages over using Travis/Appveyor (mostly appveyor).

I've verified that I can install CUDA on windows and linux images in it (+ no restart required)

## Advantages

+ Windows and linux support - (although os specific differences due to shell/filesystem)
+ Control is through the github repo - so anyone with push access can re-trigger builds (I think)
+ 60 concurrent jobs (across the org, on windows/linux images, 5 on osx)
    + 2 cores each, very large run times
+ Seems to be fast(er) (atleast my toy examples generally run quick)
+ one source of downtime instead of 3 (i.e when travis stops talking to github)
+ easy to make jobs only trigger on certain file changes / branches / PRs etc.
+ we should be able to hook in release packaging automatically (although I've not figure this out yet)
    + I.e when a tag is pushed, CI can build everythign, make a zip and attach it to the release.
+ no restarting the windows image (this was probably possible on appveyor)
+ self hosted runners

## Disadvantages
+ Cannot build with CUDA `< 10.0` on windows currently due to visual studio versions
    + Visual Studio 2019 on `windows-2019` is CUDA 10.1+
    + Visual Studio 2017 on `windows-2016` is CUDA 10.0+ (due to 2017 updates)
        + This image was going to be deprecated, but 2017 was going to be added to `windows-2019` if that were the case
    + There is discussion that 2015 might be getting installed onto the 2016 image https://github.com/actions/virtual-environments/issues/387
+ All our eggs are in one basket (but if github has an outage the others don't work either)
+ Setting paths is a bit askward / doesn't seem to work from within scripts

## Notes

I've got a few repos where i've been testing things:

+ [ptheywood/actions-playground](https://github.com/ptheywood/actions-playground)
    + cuda-less playing around with actions (to avoid ~6 min install time on windows per config, and ~ 1 min per linux)
    + Simple cmake/c++ app for testing ideas with ways to make actions efficient
    + I.e figuring out how `on.push.paths` can be used to only trigger a workflow/job if certain files are changed (i.e. anything in the `docs` directory)
+ [ptheywood/cuda-cmake-github-actions](https://github.com/ptheywood/cuda-cmake-github-actions)
    + Tested installing CUDA on both windows and linux images. Matrix of CUDA builds demonstrated. 

## Workflow Ideas

There are many ways we could organise workflows, so it is clear where problems lie / make CI faster to tell us if certain things have broken. 

+ Windows/Linux builds
    + Having a separate workflow per os image means we can have a badge for each (and the yaml is a bit simpler as we don't need to abstract OS specific stuff out.
    + Makes CUDA matrices a little easier too, as we don't need quite as complex include:/excludes: for incompaitbility
+ Separate docs workflow/job 
   + We can build the docs without needing to install CUDA, total time will be reduced due to concurrency.
+ Separate lint workflow/job
   + linting should be the same regardless of platform. With some cmake faff we could even make it so that we don't need to install CUDA to do the linting.
   + We could do this at the same time as other workflows build, this would allow us to know if the code was bad on all platforms or we just forgot to lint.
   + If this is in a separate workflow, I'm not sure if we could cancel other workflows on that commit, if its a job within the linux workflow. This might not be neccesary with 60 concurrent tasks, and matches current appveyor behaviour anyway.
+ CUDA Matrix
    + During development we probably don't *need* to know if CUDA 10.1 and CUDA 10.2 build (ie for non-master branches)
    + Once we have a release / for each actual relese, knowing it works with more versions might be useful - this should be possible with an extra workflow with minimal faff.
        + Possibly even having a way of rejecting the release if this step fails.
 + JARS
    + Self hosted runners are simply a different `runs-on` value. I.e we could have a JARS workflow which builds and executes test 
        + Github currently advise against this due to code execution as a service on public repos. ( I expect It service's new security policies might agree with this unfortunately, this holds true for jenkins too)
        + There are examples of others using runners on custom cloud instances, so we could potentially run cloud-based test's. To limit cost it would be possible to make the action only trigger if someone in the FLAMEGPU2 team adds a label / makes a specific comment in a PR for instance 

I.e. we could have the following workflows:
+ `docs` - installs doxygen and builds the docs. Only triggered by files which will effect documentation
+ `lint` - configures cmake and runs `all_lint`. - this will require changes to how our CMakeLists.txt files are structured.
+ `build/WindowsVS2019` - CUDA 10.1+ builds using VS2019, for 1 or 2 CUDA_ARCH
+ `build/WindowsVS2017` - CUDA 10.0+ buidls using VS2017, for 1 or 2 CUDA_ARCH
+ `build/Ubuntu1804` - CUDA 10.0+ builds under linux, for 1 or 2 CUDA_ARCH
+ `build/Ubuntu1604` - CUDA 8.0+ builds under linux, for 1 or 2 CUDA_ARCH

**maybe**:
+ `build/Windows2015` -  If VS2015 does appear, we can test CUDA 9.0+ on windows.
+ `release/*` - Full set of builds for OS platforms, for a broad range of CUDA versions and CUDA_ARCH values, to be ran 
+ `test/Ubuntu1804` - Build and execute tests on JARS
+ `test/cloud/*` - Build and execute tests on JARS/Cloud infrastructure
+ `perf/Ubuntu1804` - Run a benchmark suite on a self-hosted runner when requested?

I'm happy to do this at some point, although as with all CI stuff debugging it takes time. 
If so i'll do it on a fork initially, so I don't accidentally spam current CI queues while making it flame specific

**Comment by Robadob** [comment]
No reason we can't leave Travis/Appveyor active for an interim period,
otherwise support.

**Comment by ptheywood** [comment]
I've added actions to a fork (to avoid pollution) with 2 proposals for push/pr based CI (undecided on more thorough ci methods currently. comment bot vs reviews, this is less urgent). 

+ [4 workflows](https://github.com/ptheywood/FLAMEGPU2_dev/pull/1) 
    - lint, docs, ubuntu, windows as separate workflows, on push/pr. (so 8 builds per head push to a pr branch)
    - can have a badge per workflow in the readme (if desired)
    - no filtering to only trigger buids when appropriate yet (i.e. if readme is changed we can skip building the test suite)
+ [1 workflow](https://github.com/ptheywood/FLAMEGPU2_dev/pull/2)
    - lint, docs, ubuntu, windows as a single workflow
    - can only have one badge
    - a little cleaner
    - push/pr path based filters would apply to the whole workflow, rather than individual jobs. I.e. would always run ci even if only docs needs updating?) possibly not a big deal.


These still need a little work before I push the branch to upstream (can't curently tidy up old workflows from the list in the actions tab)

**Comment by ptheywood** [comment]
4 Workflow version is the preffered choice, with:

+ `Lint`
+ `Docs`
+ `Windows`
    + Subjob per Windows version being used, each with own CUDA matrix? Initiallay just VisualStudio2019
+ `Ubuntu`
    + Subjob per Ubuntu version being used, each with own cuda matrix.

Badge per job on the readme.

Triggered by all push/pr's, ideally with some filtering?

Outside this continue thinking about how releases/JARS could work.


### Todo

+ [ ] Rename workflows/jobs
+ [ ] Update badges
+ [ ] Filtering
+ [ ] Once working as intended in fork, clean history + make a PR
