### ISSUE TITLE
CUB Error Checking

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU2_dev#320]
All (most?) CUB functions return `cudaError_t`, which should be checked.

This is currently not the case, potentially leading to the errors being reported at a misleading location.

We should make sure that all `cub::` methods are wrapped in `gpuErrchk` macros.

I've not made a PR to fix this where I noticed (and used) this to identify the hardware specific issue in the swig branch, as I believe CUDAAgent has/is being refactored ?.

**Comment by Robadob** [comment]
CUDAAgent has been refactored in Submodels branch, should be in master whenever that gets merged (Probably Weds 1st July)
