### ISSUE TITLE
Agent Function Names should not need to be globally unique

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU2_dev#378]
With the current layer implementation(s) supporting `void addAgentFunction(const std::string &name);` as a way of adding an agent function to a layer, different agents cannot have the same agent function name. 

This is the behaviour in FLAME GPU 1, but it prevents (easy/clean) re-use of a common agent function for multiple agent types. 

IMO it would be nice if this requirement was not required. 

This also appears to hold be the case when the first argument of the `FLAMEGPU_AGENT_FUNCTION` definition is used to add to a layer, as that object has no understanding of which agent type is going to call it.

**Comment by Robadob** [comment]
The names are kinda redundant. Can add to layers via the agent function
description reference.

**Comment by ptheywood** [comment]
This actually causes an issue with the (currnet) RTC implemenation. 

1. make 2 agents, `a` and `b` with common properties. 
2. have an RTC function which is common between the agent types 
3. `newRTCFunction("common_string", function)` for both `a` and `b`. 

Only a single kernel will execute per layer. Changing the strings to be unique allows both to execute

**Comment by Robadob** [comment]
Ok I've located the cause of the problem.

Layer's store agent functions as a set, but lack a reference back to the parent.

Therefore, if two agents have functions with an identical name/body, the set thinks they are the same function so the 2nd one fails to add silently.

Will fix this in due course.
