### ISSUE TITLE
Code Style / Linting

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU2_dev#39]
It may be worth using a linter such as `cpplint` to adhere to some code style rules, which can be factored in as a CI phase to enforce usage. 

`cpplint` seems sensible as it supports cuda and is readily installable via pip. It can also be configured to suppress rules we do not wish to adhere to if required.

**Comment by Robadob** [comment]
Closing this, it's a duplicate of Issue #95
