### ISSUE TITLE
TestCUDASimulation.AllDeviceIdValues causes test failures on multi-gpu systems

### ISSUE THREAD

**Issue by Robadob** [FLAMEGPU/FLAMEGPU2_dev#395]
Tests haven't been run recently on mavericks. When running with `NO_SEATBELTS` in either configuration 26 tests fail. This is unusual given all test pass for both @ptheywood and I on our local machines. This was discovered on PR #371, however testing has shown the same to apply to master branch.

Seemingly in common the tests all make use of environment properties, however I haven't dug into it further than that.

Full list of failing tests:
```
[  FAILED  ] 26 tests, listed below:
[  FAILED  ] AgentEnvironmentTest.Get_float
[  FAILED  ] AgentEnvironmentTest.Get_double
[  FAILED  ] AgentEnvironmentTest.Get_int8_t
[  FAILED  ] AgentEnvironmentTest.Get_uint8_t
[  FAILED  ] AgentEnvironmentTest.Get_int16_t
[  FAILED  ] AgentEnvironmentTest.Get_uint16_t
[  FAILED  ] AgentEnvironmentTest.Get_int32_t
[  FAILED  ] AgentEnvironmentTest.Get_uint32_t
[  FAILED  ] AgentEnvironmentTest.Get_int64_t
[  FAILED  ] AgentEnvironmentTest.Get_uint64_t
[  FAILED  ] AgentEnvironmentTest.Get_arrayElement_float
[  FAILED  ] AgentEnvironmentTest.Get_arrayElement_double
[  FAILED  ] AgentEnvironmentTest.Get_arrayElement_int8_t
[  FAILED  ] AgentEnvironmentTest.Get_arrayElement_uint8_t
[  FAILED  ] AgentEnvironmentTest.Get_arrayElement_int16_t
[  FAILED  ] AgentEnvironmentTest.Get_arrayElement_uint16_t
[  FAILED  ] AgentEnvironmentTest.Get_arrayElement_uint32_t
[  FAILED  ] AgentEnvironmentTest.Get_arrayElement_int32_t
[  FAILED  ] AgentEnvironmentTest.Get_arrayElement_uint64_t
[  FAILED  ] AgentEnvironmentTest.Get_arrayElement_int64_t
[  FAILED  ] DeviceAPITest.getStepCounter
[  FAILED  ] DeviceAPITest.getStepCounterFunctionCondition
[  FAILED  ] SubEnvironmentManagerTest.SubDeviceAPIGetDefault
[  FAILED  ] SubEnvironmentManagerTest.SubDeviceAPIGetMasterChange
[  FAILED  ] SubEnvironmentManagerTest.SubSubDeviceAPIGetDefault
[  FAILED  ] SubEnvironmentManagerTest.SubSubDeviceAPIGetMasterChange

```

**Comment by Robadob** [comment]
It seems to be linked to having multiple devices available.
`CUDA_VISIBLE_DEVICES=0 ./tests`, `CUDA_VISIBLE_DEVICES=1 ./tests` (and the same for 2 and 3), all tests pass.
`CUDA_VISIBLE_DEVICES=0,1 ./tests` 26 tests fail.

**Comment by Robadob** [comment]
If the test `TestCUDASimulation.AllDeviceIdValues` is disabled, all tests pass. This test does not do anything in single device systems, hence the inconsistency.

This test runs an empty model on each device, then returns to cuda set device 0.
Not immediately clear of the problem, potentially fixed by making `CUDASimulation` perform the device change, or adding `cudaDeviceReset()`.

**Comment by ptheywood** [comment]
Running `applyConfig` again with device `0` seems a lot more sensible than the manual `setDevice(0)` I used when i originally wrote the test now that F2 has the better destruction logic.

**Comment by ptheywood** [comment]
adding a `cudaDeviceReset` to the test allows the test to pass on multi-gpu systems. 

This is not a true fix however, F2 in general needs to be a bit more device aware (singletons, init)

**Comment by Robadob** [comment]
Unconfirmed, however it appears to be a case that the singletons/device-reset-detection are getting confused over device switching.

* Run some models on Dev0, occupy singletons
* Switch to Dev1
* CUDASim detects what it thinks is a device reset
* Actioning a device reset, it purges host singletons
* Switch back to Dev0
* Host singletons were reset, so no longer match device singletons

Fix would be to add some level of multi device awareness to singletons/CUDASim
