### ISSUE TITLE
CUDA 9.X support.

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU2_dev#406]
Currenlty we vaguely claim to support `CUDA >= 9.0`. 

In `common.cmake`, we enforce `CUDA > = 7.0`.

While in `CMakeLists.txt` we enforce `CUDA >= 9.0`.

In fact I don't belive it's possible to build with some versions of 9 on some OS's at this point in time (hence CI doesn't try). 
In practice, now that 11.0 and 11.1 are out, it seems sensible that we support the last 2 major releases (at the approx time of flamegpu2 being released) which maps to 10.0+. 

This won't change any support in terms of hardware (Kepler can still be used on 10). 

I think i was the main block to this being the case originally, as at the time 10.x wasn't deployed on various HPC systems. This is still true for 11.x at the time of writing. 

+ [x] Update readme
+ [x] Switch CI to run min/max  (10.0 + 11.1?)
+ [x] Consistent CUDA version checking in common.cmake and CMakeLists.txt
+ [x] Remove mentions / specialisations for older CUDA.

+ [x] If not yet done, upgrade windows CI to 11.1 update 1.

I'm happy to do this if agreed upon.

**Comment by Robadob** [comment]
Sounds good to me, definitely something to do prior to release (maybe worth leaving till then incase 11.2?).

**Comment by ptheywood** [comment]
Minimum version won't change, and switching CI to 11.2 will be trivial, probably won't even mention the max cuda verison anyway. 

The other thing to consider would be what Cmake version do we want as a minimum, and if you have python3 + pip you should be able to install the latest cmake wherever you are.

**Comment by Robadob** [comment]
I think it was cmake 3.18 min required off top of my head for blocking cuda
linker warnings on windows.

**Comment by ptheywood** [comment]
Yep 3.18 added that, though we have that optionally enabled, so we can certainly recommend 3.18+, although I'd be reluctant to require it (it's still the latest minor version, even though pip should be an option most places where users may not have root.)

We might want to recommend VS 2019 on windows, but support 2017+ as recent thrust has dropped support for VS 2015 (though I don't think they've broken VS 2015 yet, just its no longer being planned for / tested).

**Comment by Robadob** [comment]
I've never really used 2017, so not too bothered whether it's supported or
not. But it should work, if Thrust was the only reason vs 2015 got tenuous.

**Comment by ptheywood** [comment]
+ [ ] Plan 10.0+ supported, with a note taht < 11 + MSVC might have tempremental build failures.
+ [ ] Disable 10.2 on windows.
