### ISSUE TITLE
StepCounter logic  with multiple calls to Simulate()

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU2_dev#410]
If a second call is made to `simulate()` without a call to `reset()` what should happen?

I.e. if the simulation config says a simulation is `4` steps, simulate will execute steps `0, 1, 2, 3`. A subsequent call to `simulate` will run steps `4, 5, 6, 7`. 

Should this actually be the case? Or should the second call to `simulate` not do anything as step `3` has already been executed? 

There is also the interaction with explicit calls to `step()`. I.e. how many steps should be executed if the config is for `4` steps, but calls are `step(); step(); simulate();`. Should this execute 6 steps, or just 4?.

Changing this might break tests (or atleast change behaviour from intended.).

**Comment by Robadob** [comment]
There's already an issue for this.

#265

**Comment by ptheywood** [comment]
My bad for not looking. Will close this (and duplicate the body as a comment).
