### ISSUE TITLE
Feature: Layer - Host functions

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU2_dev#47]
Host functions as a part of layers. 

Ideally these should be able to execute concurrently with agent functions in the same layer, though this would have to be clearly documented. 

Not an urgent feature, complicates dependency analysis

**Comment by Robadob** [comment]
This is being used within PRIMAGE too.

**Comment by ptheywood** [comment]
There will probably need to be a host version of the `FLAMEGPU_API` object (with a differnt name / rename the GPU version too). 

We will need to be very careful with concurrency when implementing this. 
If a host layer-function can be executed at the same time as device functions FLAME GPU API calls should be restricted to prevent race conditions. 

I.e.
If a host layer functions access agent data for an agent which is executing an agent function, it shouldn't be able to write to or read from that agent (i.e. maintain the only one agent function per statelsit rule)
This will need dependency analysis to do upfront, otherwise some form of locking of various bits of the api subject to what is running.
