### ISSUE TITLE
Feature: Agent Death

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU2_dev#49]
Death of agents from device agent functions.

**Comment by Robadob** [comment]
Started working on this in 'agent_death' branch, noticed a few quirks with optional messaging at same time.

Rough todo:
* Add resize method to CUDAAgentStateList
* Add set Count method to CUDAAgentStateList (perhaps this can merge with above)
* Ensure flamegpu_internal::resize_agent_scan_flag(max_list_size); is called on CUDAAgentStateList resize()
* Ensure both message and agent d_scan_flag arrays are zero'd in relevant map variables methods when use is required.

**Comment by Robadob** [comment]
Both agent death and optional messages should be working now (although not on master, see above commit), however I'm yet to unify their handling of variable scatter.

It's also up for debate whether the scan flag should always be written to, regardless of whether there is agent death allowed. (And whether we should ensure only 0 or 1 is written.

**Comment by Robadob** [comment]
This is now ready for merge into master
