### ISSUE TITLE
Example: EmptyExample

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU2_dev#59]
Provide a hello-world esque example which can be used with some script(s) to create a new example.

**Comment by Robadob** [comment]
I've been thinking about this. It would be better positioned in a separate repo (and linked to from this repos README).

Using CMake magic, similar to GTest, it should pull in the main repo and build/link with FGPU2 static lib. This would be far more useful to users, as an example they could quite literally fork and work from. It would simply need a little bit of documentation explaining how to direct it at a specific commit/release of FGPU2 and how to manage the `CMakeLists.txt` to rename project/similar.

**Comment by Robadob** [comment]
https://github.com/FLAMEGPU/FLAMEGPU2_example_template
