### ISSUE TITLE
Documentation: User Guide

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU2_dev#70]
Explicit user-friendly documentation. i.e getting started etc. 

The readme should be user-friendly first, developer friendly second (do this down the line).

**Comment by Robadob** [comment]
It would be useful for this to be progressively written, it's contents could function as a useful list of current;y available functionality.

**Comment by Robadob** [comment]
Closing this. Userguide has it's own repo for user guide issues and there's a big issue for updating the readme somewhere too.
