### ISSUE TITLE
Detailed Visual Studio instructions in Readme

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU2_dev#75]
To debug one of the executables in visual studio, several steps must be taken on a per-machine basis.

+ The executable to be run must be set as the "Startup Project" by right clicking on the project and selecting "Set as Start Up Project", otherwise the debugger will try to run the static library file...
+ Any command line arguments will need to be set on a per-machine basis in the debug settings menu. This must be done per configuration (debug/release/profile(future))

**Comment by Robadob** [comment]
I'll fix this at some point, only question is whether we want to include screenshots in the readme.
