### ISSUE TITLE
Feature: SubModels - Iterative Blocks

### ISSUE THREAD

**Issue by Robadob** [FLAMEGPU/FLAMEGPU2_dev#81]
Primage model in two instances has a need to run multiple agent functions for an unknown number of iterations until an optimisation has reached an end point.

It was agreed that this could be modelled as a sub-model, which inherits from a parents model, executing until an exit condition is satisfied.

This would require:
* agent variable mappings
    * Optional read only access
* Read only message access
* Environment bound mappings? (spatial messages need env bounds for best case perf)
    * This could be performed by doing scaling inside spatial message handling?
* Optional override of central model fn?
* Exit condition

```xml
<submodels>
    <submodel>
        <name>BondingModel</name>
        <modelfile>bonding.xml</modelfile>
        <mapping>
            <environmentMapping>
                <!-- Perhaps an env variable needs to be shared between models. -->
            </environmentMapping>
            <agentMapping>
                <name>Boid</name>
                <subName>BondingAgent</subName>
                <variable>
                    <name>x</name>
                    <subName>x</subName>
                <variable>
                <variable>
                    <name>y</name>
                    <subName>y</subName>
                <variable>
                <variable>
                    <name>z</name>
                    <subName>z</subName>
                <variable>
                <!--Agent force variables can be wholly contained within bonding model.-->
            </agentMapping>
            <messageMapping>
                <!--Perhaps read only access to some messages is required-->
            </messageMapping>
        <mapping>
        <bounds>
            <!--Bonding submodel has its own spatial partitioning, somehow we need to configure the env bounds (and radius)-->
            <fromMessage>
                <name>location_message</name>
            </fromMessage>
        <bounds>
        <function>
            <!--Optional replacement for bonding condition, e.g. protein level check + rng-->
        </function>
        <exitCondition>
            <reduction>
                <agentVariable>
                    <agent>BondingAgent</agent>
                    <variable>ForceMagintude</variable>
                </agentVariable>
                <operator>+</operator>
                <condition>&lt;0.01</condition>
            </reduction>
        </exitCondition>
    </submodel>
</submodels>
....
<layers>
    <layer>
        <gpu:layerFunction>
            <name>doSomething</name>
        </gpu:layerFunction>
    </layer>
    <layer>
        <subModel>
            <name>BondingModel</name>
        <subModel>
    </layer>
    <layer>
        <gpu:layerFunction>
            <name>doSomethingElse</name>
        </gpu:layerFunction>
    </layer>
</layers>
```

**Comment by Robadob** [comment]
cc @mondus 
In terms of a FGPU2 interface I expect it will look similar to this
```C++
// Define the sub model 'bonding_model'
ModelDescription bondingModel("bonding_model");
{
    AgentDescription &bondingAgent = bondingModel.newAgent("agent");
    bondingAgent.newVariable<float>("x");
    bondingAgent.newVariable<float>("y");
    // Submodels MUST contain atleast 1 exit condition
    bondingModel.addExitCondition(SomeExitCondition);
    // TODO .. Define rest of 'bonding_model', messages, layers etc
}

// Define the host model
ModelDescription tumourModel("tumour_model");
{
    AgentDescription &cellAgent= tumourModel.newAgent("cell");
    cellAgent.newVariable<float>("x");
    cellAgent.newVariable<float>("y");
    // TODO .. Define rest of 'tumour_model' agents/messages
   
    // Add sub model
    SubModelMap &bondingLink = tumourModel.addSubModel("bonding_sub", bondingModel);
    // Define mapping for submodel
    // parent agent name, child agent name, automatically map compatible variables (same name/type/length)
    SubAgentMap &cellMap = bondingLink.mapAgent("cell", "agent", true);
    cellMap.mapVariable("x", "x");  // Manual version also available

    // Add submodel to execution (submodel must be in it's own layer)
    tumourModel.newSubModelLayer("bonding_sub");
    // TODO .. Define rest of 'tumour_model' layers
}
```

**Comment by Robadob** [comment]
In terms of `CUDAAgentModel` implementation.

`CUDAAgent` will have a derived type `CUDASubAgent`, and `CUDAAgentModel` a private constructor (which takes a parent model).

Final stage of constructors (both, submodels will be recursive) will initialise a `CUDAAgentModel` for each sub model. The private constructor will instead init agents as `CUDASubAgent`, these will kind of act as a proxy over the mapped `CUDAAgent`, defining unmapped vars with the normal allocation, and deferring mapped accesses to the master model.

Sharing of environment properties (and messages?) will require a bit more thought, but likely follow similar paths.

**Comment by ptheywood** [comment]
w.r.t parentless submodel agents, they could be specified in an init function on the submodel. Loading from disk feels like it shouldn't be supported for these temporary (?) agents. 

Whether they persist or not between submodel invocations probably depends quite heavily on the model, so it may be worth supporting both? Although I've not got an example for this usage off the top of my head. 

A submodel init function, with a simple if statement to check if the pop already exists would work for initialising agents which survive between invocations.

We could potentailly make this case the default, and expect users to run an agent function (or an exit function?) which kills the temporary agent if that is desired behaviour, although this would likely be more costly than resetting agent properties in an once-run submodel function (or a reset from the host?)

**Comment by Robadob** [comment]
For the time being I'm just going to try and get a basic mapped agent submodel demo working, then these edge cases an be added after.

**Comment by Robadob** [comment]
So the handling of `CUDAAgent`, or more precisely `CUDAAgentStateList` is going like this.

`CUDAAgentStateList`  has an optional member `dependent_list`.

Any operations which modify the buffers, or number of alive agents is also propagated to `dependent_list` (which is then recursive, as it may have its own dependent). Such that any bound agent states will always have the operations performed on all buffers bound to the master agent state.

Much of this is trivial, e.g. `current_list_size` is just set in 2+ places rather than 1.

More complicated is scan/scatter behaviour.

Normally we just pass the variable map (variable name: variable type/size info), d_list, d_swap_list maps (variable name: device pointer) to `CUDAScatter`. Now however, we create a `Merge` map which contains each unique variable across all dependant agent states, and pass that to `CUDAScatter`.

*(In writing this, I've just clocked that my solution for variable name clashes in the map is flawed beyond a depth of 1 submodel), it would make sense to move the construction of the `ScatterData` list to outside `CUDAScatter`, would mean we don't have to dance around name clashes and likely be more efficient.*

**Comment by Robadob** [comment]
Re: Thoughts on moving agents between mapped/unmapped agent states

The strategy seems to be what i've outlined below.
Currently the top two should work, but the bottom two are set to throw assertions.
I don't really like how the code to manage all this is structured, and im trying to conjure a cleaner method.
```
in[not mapped]->out[not mapped] = No mergelist required, this is old method
in[mapped]->out[mapped] = Mergelist is perfect match
in[mapped]->out[not mapped] = Any temporary variables in the mapped agent state can be dropped as they are nolonger required
in[not mapped]->out[mapped] = Uninitialised temporary variables are created for the agents (it's assumed within the model they are initialised before use)
```

Similarly
If we have nested sub models
`AgentA->AgentB->AgentC`

If `AgentB` cant map the input state, then the same MUST be true for dependent `AgentC`.

If `AgentB` can't map the output state, then the same MUST be true for dependent  `AgentC`

**Comment by Robadob** [comment]
Maybe also a case for sharing agent_birth buffers between all agents.
Store them in descending size order, and assign them largest first. (Tracking pop size, rather than buffer size to decide when to resize/add new buffer).

They're currently allocated per agent when required, but this could save memory if different agents give birth in different layers.
