### ISSUE TITLE
Graceful device error handling/logging

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU2_dev#88]
In some cases it could be useful to exit the simulation gracefully if a device-side issue is encountered. 

I.e. an agent with a variable encoding an id, but it is set to an invalid value such as `UINT_MAX`. This could be caught with an `assert` by the user, but this would generate either many lines of error, and/or a not very user friendly error.

**Comment by Robadob** [comment]
This should be easy to implement.

Allocate a __device__ bool and char, create a macro which wraps and device function, allowing users to do a condition + error string (also output offending file/line no.

Could also `#undef assert`

**Comment by Robadob** [comment]
Something like this? https://gist.github.com/Robadob/f12af24a3e3c3ab8ed2c228061262eb5

Wouldn't be too much work to make it support a longer buffer/multiple messages.

**Comment by ptheywood** [comment]
I don't think that'll compile, `printf` is the only `__device` print related function as far as I am aware. 

https://docs.nvidia.com/cuda/cuda-c-programming-guide/#formatted-output

This also clears up why `printf`s in device code can cause different errors to occur (order of execution is likely changed). 

We'd probably instead have to store some form of error code (an int etc) in device mem, rather than a string and copy that back, though we'd lose any opportunity for logging the actual values.

**Comment by Robadob** [comment]
Maybe this will work on device.

https://github.com/nothings/stb/blob/master/stb_sprintf.h

Probably expensive af, but if they're getting/logging errors it's not like performance matters.

**Comment by Robadob** [comment]
https://nvlabs.github.io/cub/group___util_mgmt.html#ga5a175d2a88f63f7f1ab30e8b4f2cfa95

Not sure if this cub device debug function is relevant.

**Comment by Robadob** [comment]
Made a fork of the branch in #144 to work on this, a few key lessons:

* With a few tweaks, it's possible to `vsnprintf()` using the stb header version.
* It appears all CUDA errors triggered from device code are 'non-sticky', such that the CUDA context is corrupted and no further CUDA calls can be executed until `cudaDeviceReset()` (and in some cases full process termination).
  * Therefore it would require a regular `cudaMemcpyFromSymbol()` or similar to detect a graceful failure flag.
  * Without triggering an exception, it might not be possible to guarantee that beyond our error state detection, the issue doesn't propagate causing a stick-error before the kernel's natural exit. (I don't think we can `goto: kernel end`, can you label across files/function?)

**Comment by mondus** [comment]
Lets make this Debug only and then add the cmake faf for "fast no seat-belts" later
