### ISSUE TITLE
Test CMake configuration on Windows

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU2_dev#91]
I'm not 100% the current CMake configuration has been tested on Windows.

**Comment by Robadob** [comment]
There isn't a `CMakeLists.txt` in the repo, I can't test it.

**Comment by Robadob** [comment]
Built the version from `dev/2-Messages`, using Visual Studio 2015, CUDA 10.1

Succeeded, however there were a million warnings, log from debug build listed [here](https://gist.github.com/Robadob/efa85ee7e17e995e807fc2a040befcb4).

**Comment by ptheywood** [comment]
@Robadob I've pushed branch dev/2-Messages-msvc-warnings which should downgrade to W4 on msvc. GCC behaviour is as before (tested).

**Comment by Robadob** [comment]
Unsure if changing it via -Xcompiler is the correct behaviour for visual studio (see below), but i'll give it a play soon.

![image](https://user-images.githubusercontent.com/742154/67564789-aec78600-f71b-11e9-987d-63668d0a7bad.png)

**Comment by ptheywood** [comment]
True, it will probably only have set it for CUDA files, rather than any cpp files.

Xcompiler forwards flags through to the host compiler from NVCC, so perhaps instead setting it for the CXX compiler would do what we want. 

As with most things cmake it seems like there are a million and one ways to do this and finding the current "correct" way is a faff.

**Comment by Robadob** [comment]
Closed, merged with #100
