### ISSUE TITLE
Linting

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU2_dev#95]
> **Status:**
> Branch `lint-fix` has complete linting of all projects with several exceptions:
> * TODO rule has been disabled
> * line length has been increased (to 240?)
> * const-reference has not been resolved (need to discuss with Paul, whether he wants rule followed)
> * include/subdirectory has not been resolved within tests (as all files in same dir, includes would take form `"./test_foobar.h"), might resolve this by restructuring tests.
>
> *Note: Renamed `device_functions.h/cu` to `device_test_functions.c/cu`, the previous header  name was shared with a deprecated CUDA header, as such it was breaking travis.*
>
> Robert

Linting code to semi-enforce style is probably worthwhile. 

Current cmake files (dev/2-messages) adds an extra target per project for running the linter, so for Makefiles this can be `make lint` on a per-project basis. 

In VS this generates an extra project, which I'm not sure actually runs cpp lint.

Cmake appears to have partial integration for cpplint, but only with Makefiles. 

Alternatively, `clang-tidy` might be an option. Worth investigating. 

Some links for future reading: 

+ https://sarcasm.github.io/notes/dev/clang-tidy.html#cmake-integration
+ https://gitlab.kitware.com/cmake/cmake/issues/18808

Some probably things to do:

+ [x] Detect if cpplint is installed, don't call it if not (at cmake time, output a message?)
+ [x] Don't lint third party code (i.e. tinyxml.h)
+ [x] Customise cpplint rules? 
    + [x] Disable lint rule for non-const references (they're useful for python integration) (f31c040)
+ [x] `lint` target to `all_lint`
+ [x] Fix linting error
+ [x] Revert any accidental find-replace changes to tinyxml.
+ [x] Restructure the tests directory for concistency (ce8c9c4).
+ [x] Enforce linting on CI (7c3ba51, travis only).

**Comment by Robadob** [comment]
> Detect if cpplint is installed, don't call it if not (at cmake time, output a message?)

688c552132925b2d22b15b44298474b343cfe831 addresses this, tested on windows, should work on Linux

**Comment by ptheywood** [comment]
as of 1e05cd1, under linux `all_lint` stops after the first sub-target fails. I.e. 

```
make all_lint
/home/ptheywood/code/flamegpu/flamegpu2_dev/tests/test_all.cu:30:  Include the directory when naming .h files  [build/include_subdir] [4]
/home/ptheywood/code/flamegpu/flamegpu2_dev/tests/test_all.cu:31:  Include the directory when naming .h files  [build/include_subdir] [4]
/home/ptheywood/code/flamegpu/flamegpu2_dev/tests/test_all.cu:32:  Include the directory when naming .h files  [build/include_subdir] [4]
/home/ptheywood/code/flamegpu/flamegpu2_dev/tests/test_all.cu:33:  Line ends in whitespace.  Consider deleting these extra spaces.  [whitespace/end_of_line] [4]
/home/ptheywood/code/flamegpu/flamegpu2_dev/tests/test_all.cu:33:  Include the directory when naming .h files  [build/include_subdir] [4]
/home/ptheywood/code/flamegpu/flamegpu2_dev/tests/test_all.cu:34:  Line ends in whitespace.  Consider deleting these extra spaces.  [whitespace/end_of_line] [4]
/home/ptheywood/code/flamegpu/flamegpu2_dev/tests/test_all.cu:34:  Include the directory when naming .h files  [build/include_subdir] [4]
Done processing /home/ptheywood/code/flamegpu/flamegpu2_dev/tests/test_all.cu
Total errors found: 7
tests/CMakeFiles/lint_tests.dir/build.make:57: recipe for target 'tests/CMakeFiles/lint_tests' failed
make[3]: *** [tests/CMakeFiles/lint_tests] Error 1
CMakeFiles/Makefile2:390: recipe for target 'tests/CMakeFiles/lint_tests.dir/all' failed
make[2]: *** [tests/CMakeFiles/lint_tests.dir/all] Error 2
CMakeFiles/Makefile2:82: recipe for target 'CMakeFiles/all_lint.dir/rule' failed
make[1]: *** [CMakeFiles/all_lint.dir/rule] Error 2
Makefile:118: recipe for target 'all_lint' failed
make: *** [all_lint] Error 2
```
has only ran `lint_tests`. 

This might be a feature of Make rather than a bug however, as if a dependency of something fails, why bother running the rest.

**Comment by ptheywood** [comment]
As of f9bf1a9

```
make lint_flamegpu2 2>&1 | tee lint.log

grep "^/" lint.log | cut -d"[" -f2 | cut -d"]" -f1 | sort | uniq -c
     39 build/header_guard
      1 build/include
     48 build/include_order
      3 build/include_subdir
     10 build/include_what_you_use
      5 build/namespaces
     13 readability/braces
     23 readability/casting
      8 readability/todo
     13 runtime/explicit
     22 runtime/references
    106 whitespace/blank_line
    309 whitespace/braces
      2 whitespace/comma
    327 whitespace/comments
     24 whitespace/end_of_line
      1 whitespace/forcolon
     50 whitespace/indent
      8 whitespace/line_length
      6 whitespace/newline
      7 whitespace/operators
      8 whitespace/parens
      1 whitespace/semicolon
```

**Comment by ptheywood** [comment]
As of 95dcc75 with the line length of 120, 8 if linelength=200

```
grep "^/" lint.log | cut -d"[" -f2 | cut -d"]" -f1 | sort | uniq -c
      2 build/include
      8 build/include_order
      3 build/include_subdir
      8 readability/todo
      5 runtime/explicit
     22 runtime/references
      1 whitespace/braces
      8 whitespace/comments
      1 whitespace/ending_newline
     82 whitespace/line_length
```

**Comment by Robadob** [comment]
Have moved work into branch `lint_fix`, cherry-picks changes from `upstream/dev/2-Messages-lint` onto `master`.

Will delete old branch now.
