### ISSUE TITLE
Remove explicit visual studio files

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU2_dev#96]
Switching to Cmake for windows and linux builds removes duplication of project configuration for development. 

Appveyor will also need updating to account for this. 

@mondus @mozhgan-kch are you both happy with this?

**Comment by Robadob** [comment]
**Context:**
I've updated CMAKE config in #93 (the branch attached to this pull request) to support visual studio properly, and fix bug/s, so I feel it's ready for use on Windows.

**Note:**
These changes (fix and) make linting not included as part of `ALL_BUILD`, so it may be worth enforcing lint on CI at some point in future (after linting issues in code base have been resolved).

**Comment by ptheywood** [comment]
This would also enable the removal of `lib/Release` and `lib/Debug`. 

We should also think about where binary files and library files are placed, so that users can specify custom output directories to cmake  which should probably contain `bin` and `lib`.
