### ISSUE TITLE
.gitignore rules

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU2_dev#99]
.gitignore needs configuring to ignore cmake generated files on both windows and linux. 

Currently if users generate in a `build` directory all files will be ignored, but not if the user builds in a different directory. 

+ https://github.com/github/gitignore/blob/master/CMake.gitignore
+ https://github.com/github/gitignore/blob/master/VisualStudio.gitignore

**Comment by Robadob** [comment]
Looking at the .gitignore, it already contains visual studio, albeit 5 years old, so maybe out of date
